### ISSUE TITLE
Element saml:AuthnContextDeclRef cannot be parsed

### ISSUE THREAD

**Issue by hotstepper13** [Uninett/mod_auth_mellon#183] opened 2018-10-05 17:21 UTC
We are using the mod_mellon debian package (0.14.0-1+b1) within a docker container.

The IDP which we are connected to, recently updated the software and since then we got some errors. I was already able to fix most of them but after the redirect from us to the idp, successful authentication and routing back to us, we can see the above mentioned error message in our logs.

I have checked the documentation and our configuration and we have not set MellonAuthnContextClassRef. 

As part of the debugging we have updated mod_mellon to the latest version (as stated above). Previous we were working with 0.13.1-1.

The full error message from apache is

    (process:8): Lasso-ERROR **: 15:23:05.097: 2018-10-05 15:23:05  Element saml:AuthnContextDeclRef cannot be parsed
    [Fri Oct 05 15:23:05.225085 2018] [core:notice] [pid 7:tid 140031418688576] AH00052: child pid 8 exit signal Trace/breakpoint trap (5)

I would like to know if this is clearly an issue from the IDP, from mod_mellon or if there is any change to "mitigate" this issue within our configuration.

Thanks in advance and best regards

Frank

**Comment by hotstepper13** [comment] 2018-10-10 05:50
Update, I was able to retag an older docker container that uses Mellon 0.13.1 and with this version the issue doesnt appear.

**Comment by olavmrk** [comment] 2018-10-10 09:41
Hi,

my guess is that the older container image also has a older version of the Lasso library, and newer versions of the Lasso library does some parsing of the `<saml:AuthnContextDeclRef>`-element in the response.

To properly diagnose the problem, you probably need to look at the contents of that element in the SAML authentication response.

(I don't think I have ever seen that element used, so I don't know how it is supposed look. I have only seen `<saml:AuthnContextClassRef>`-elements (with `Class` instead of `Decl`) used, and I believe that is for signaling authentication methods.)

**Comment by thijskh** [comment] 2019-08-27 07:23
We ran into the same issue, this was with NetIQ AM as an IdP.

It turned out to be caused by the following issue in liblasso:
https://dev.entrouvert.org/issues/25640
The referenced patch works for us.

I've asked the lasso dev to tag a new release of lasso.

**Comment by olavmrk** [comment] 2019-09-30 07:05
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md

**Closed by olavmrk** 2019-09-30 07:05 UTC
