### ISSUE TITLE
Error processing authn reponse. Lasso error: [-428] Missing Subject

### ISSUE THREAD

**Issue by ismailseyfi** [UNINETT/mod_auth_mellon#51] opened 2015-09-04 19:17 UTC
Hi, 
We have been using mellon successfully for a while now integrating with our IDP server which is WSO2. Recently we wanted to use one of their capabilities to exchange a SAML assertion for an OAUTH token. In order to achieve this we have to add an additional SubjectConfirmation element. Here is how are Subject element looks when we get this error.  It seems mellon has a problem dealing with this. How can we fix this? 
&lt;saml2:Subject&gt;
      &lt;saml2:NameID Format=&quot;urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress&quot;&gt;user&lt;/saml2:NameID&gt;
      &lt;saml2:SubjectConfirmation Method=&quot;urn:oasis:names:tc:SAML:2.0:cm:bearer&quot;&gt;
        &lt;saml2:SubjectConfirmationData InResponseTo=&quot;_A8AB42D97072E4FD22385BF39E1E7332&quot; NotOnOrAfter=&quot;2015-09-04T19:12:57.841Z&quot; Recipient=&quot;https://localhost/abcd&quot;/&gt;
      &lt;/saml2:SubjectConfirmation&gt;
      &lt;saml2:SubjectConfirmation Method=&quot;urn:oasis:names:tc:SAML:2.0:cm:bearer&quot;&gt;
        &lt;saml2:SubjectConfirmationData InResponseTo=&quot;_A8AB42D97072E4FD22385BF39E1E7332&quot; NotOnOrAfter=&quot;2015-09-04T19:12:57.841Z&quot; Recipient=&quot;https://localhost/xyz&quot;/&gt;
      &lt;/saml2:SubjectConfirmation&gt;
    &lt;/saml2:Subject&gt;

**Comment by olavmrk** [comment] 2015-09-16 07:57
It appears that the [Lasso library API](http://lasso.entrouvert.org/documentation/api-reference/lasso-LassoSamlSubject.html) does not allow for more than one `<SubjectConfirmation>`-element, so there is no way that we can support this. This is also probably why the Lasso library gives an error when parsing your message.

But why do you need to include two `<saml:SubjectConfirmation>`-elements? I have never seen that in use elsewhere.

Is it because you are issuing an assertion that is valid for two different URLs? In that case, since you are only sending it to a single URL, why don't you just include the actual destination URL? After all, you already need to know the desination URL in order to add it to the `Destination` attribute on the `<samlp:Response>`-element.

**Comment by ismailseyfi** [comment] 2015-09-16 13:34
Its actually going to two different URLS. We are exchanging our SAML
assertion for an OAUTH token. OAUTH token issuer is the second URL. What is
the process for you to make change requests to your dependent projects? is
there one? Do we directly go to them ask them to add this capability to
their APIs?

thanks
Ismail

**Comment by olavmrk** [comment] 2015-09-16 14:15
Wait, are you sending one SAML 2.0 response, containing one SAML 2.0 assertion to two different URLs at once? That does not make sense?

As for change requests to the Lasso library, I don't know if they have a policy. There is a mailing list that I usually send them to: http://listes.entrouvert.com/info/lasso

However, before going in that direction, I would strongly encourage you to create a clear description of what you are doing, and why you need to do it this exact way. You appear to currently be doing something way outside of the normal SAML 2.0 Web SSO flow.

I'm closing this issue for now. If the Lasso library adds support for parsing multiple SubjectConfirmation elements, we can certainly add support for processing them in mod_auth_mellon, but since I do not understand your requirements, I cannot be the one that brings that request to the Lasso developers.

**Closed by olavmrk** 2015-09-16 14:15 UTC

**Comment by ismailseyfi** [comment] 2015-09-16 14:47
Thanks for the information.

Take a look at this. This should give you a good explanation.

https://docs.wso2.com/pages/viewpage.action?pageId=45944343

We have an SP that is protected by mellon. It successfully gets a SAML
assertion. This SP then uses OAUTH to access some APIs. In order to get an
access token for this SP for OAUTH, we are using this SAML assertion and
exchanging it for an access token. That requires this Assertion to be
consumed by another entity (token issuer if you will). This is a common
grant type.

thanks
Ismail

**Comment by olavmrk** [comment] 2015-09-16 16:14
Thanks for the link! Interesting way to (ab?)use of the SAML 2.0 specification. Looking at [RFC 7522](https://tools.ietf.org/html/rfc7522) and a few of the top hits on Google for [oauth 2.0 saml bearer assertion flow](https://google.com/search?q=oauth+2.0+saml+bearer+assertion+flow) I don't see any signs that it was actually intended that the generated assertion was intended to be used by two different SPs.

In any case that is not really my problem to figure out. If you can convince the developers of the Lasso library to parse this in some way, I don't really see a problem of adding support for processing it in mod_auth_mellon, as long as it can be added in a way that also allows mod_auth_mellon to work with existing versions of the Lasso library.

I can't promise to write the required changes in mod_auth_mellon before I see what changes are required and what else I have to work on at that time. If I don't have time to write the changes myself, I would at least accept a cleanly written patch that implements it.

**Comment by ismailseyfi** [comment] 2015-09-16 16:27
Thanks. Sounds fair. I will make an inquiry with them and see what happens.

thanks for your time.
Ismail
